### ISSUE TITLE
monthPid is not recognized

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/calendarize#761] opened 2023-10-05 11:17 UTC
I added `monthPid` in TypoScript as well as in a calendarize record, nevertheless the debug output in `Month.html` doesn't list it. I suspect it might be dependent on `yearPid` or have a similar logic but I never looked it up.  
As I need only `monthPid` to display the month-navigation I never care about the unneeded pids.  
I made a workaround in the template which takes the `listPid` if `monthPid` is empty, so I got it working, but I'd expect that an entered variable is recognized and used.

**Comment by lochmueller** [comment] 2023-10-06 11:09
Could you add your EXT:calendarize version?

**Comment by DavidBruchmann** [comment] 2023-10-06 11:46
Sure, thanks for having a look!

calendarize: 12.4.4  
TYPO3 11.5.21

**Comment by okmiim** [comment] 2023-10-22 13:53
Hi @DavidBruchmann,

You have a Calendarize plugin in the `Month` mode. In the `Page ID configuration` you have set the `Month PID [settings.monthPid]` to the same page(?).
In the fluid template, you now try to access `settings.monthPid`, similar to the following snippet
https://github.com/lochmueller/calendarize/blob/b109e0b9b181b7c68c89d04a9785682e75b1b67d/Resources/Private/Partials/Month.html#L7-L13

- Corresponds this to you setup?
- In your case the `settings.monthPid` is empty?
- In my testing I could not reproduce that.
- Do you have any more details?

_Note: setting the `settings.monthPid` from TypoScript will not work, since the flexform will always overwrite it (even if empty). We don't have setting like `overrideFlexformSettingsIfEmpty`(News)._

**Comment by DavidBruchmann** [comment] 2023-10-22 15:30
Hi @okmiim , 

thanks a lot, I suspect with this hint I can solve the issue.
It takes me 2-3 days probably and will report back.
So long I leave it open.

**Comment by lochmueller** [comment] 2024-03-11 20:43
I close this issue, because there is no more progress. 

Feel free to reopen it, if there are any news or open problems related to this in EXT:calendarize.

**Closed by lochmueller** 2024-03-11 20:43 UTC
