### ISSUE TITLE
Wrong categories assigned in keSearchIndex / ke_search Index

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize#432] opened 2020-09-18 14:54 UTC
The categories are assigned wrong, while indexing calendar events with ke_search. All events get the category / categories from the first event.

Seems there is something wrong in **function getKeSearchTags** in Domain/Model/Event.php

    public function getKeSearchTags(Index $index): string
    {
        static $keSearchTags = [];
        if (empty($keSearchTags)) {
            foreach ($this->getCategories() as $category) {
                $keSearchTags[] = "#syscat{$category->getUid()}#";
            }
        }

        return \implode(',', $keSearchTags);
    }

changed to is working

    public function getKeSearchTags(Index $index): string
    {
        static $keSearchTags = [];

            foreach ($this->getCategories() as $category) {
                $keSearchTags = array();
                $keSearchTags[] = "#syscat{$category->getUid()}#";
            }

        return \implode(',', $keSearchTags);
    }

PHP 7.2-latest FPM
calendarize 6.0.0
ke_search 3.2.0
TYPO3 9.5.21

**Comment by lochmueller** [comment] 2020-09-19 11:52
Hey @sdesign6 
Thanks for the report. The problem is the static variable. Your could would also not working, because it only use the last category of the event item, because you reset the "keSearchTags" ecah iteration. Temporary solution could be, just remove the "static" in the method. I will check this and will fix this in the current master.
Regards,
Tim

**Comment by lochmueller** [comment] 2020-10-02 21:37
Fixed in next release.

**Closed by lochmueller** 2020-10-02 21:37 UTC
