### ISSUE TITLE
Event is not showing up in weekView with weekStart setting

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize#428] opened 2020-09-15 18:07 UTC
An event on sunday does not show up in weekview, when plugin.tx_calendarize.settings.weekStart = 1. Only if weekStart = 0.

TYPO3 9.5.20
calendarize 6.0.0 
PHP 7.2.33

**Comment by lochmueller** [comment] 2020-12-20 17:22
@okmiim Does the last PR fix this problem? Because it is DateTime related.

**Comment by okmiim** [comment] 2020-12-21 12:09
I couldn't reproduce the behavior exactly.
However there was an issue (there were probably some more), where events being listed one day to early (e.g. timezone utc-01).
This resulted no events to show up on sunday. 

This issue could be something similar.

**Comment by lochmueller** [comment] 2021-05-06 14:39
hey @sdesign6 & @okmiim 

I also try to reproduce the problem with the current version (and TYPO3 v10) and cannot confirm this bug. I think it is a problem of the old release. It is recommended to update to new releases.

I will close this issue.

If you can reproduce the problem with the current master of the extension, feel free to reopen the issue and add some more details related to this bug.

Regards,
Tim

**Closed by lochmueller** 2021-05-06 14:39 UTC
