### ISSUE TITLE
ICS-Import create duplicates 

### ISSUE THREAD

**Issue by Raymondsnijders** [lochmueller/calendarize#381] opened 2020-03-06 10:16 UTC
Hi Tim,

I have the current master installed. Did the importtask but it still imports all the records. So I get duplicates. The exisiting records maybe deleted, updated or ignored during the import.

Thanks,
Raymond

**Comment by lochmueller** [comment] 2020-03-06 11:55
Please add the TYPO3 version and (if possible) the URI to the imprted ICS file.
Thank you.

**Comment by Raymondsnijders** [comment] 2020-03-06 12:24
Typo3 9.5.14

https://outlook.office365.com/owa/calendar/f9731c3b65f14ab098cd39a58304e492@de-mare.org/12cceb4ad1f44fc1b2918810fee0932117963174705084742764/calendar.ics

**Comment by lochmueller** [comment] 2020-03-06 14:38
Hey @Raymondsnijders 
The problem is the ICS generation in office365. The UID of the entries is in every generation another ID. So a mapping incl. an update ia not possible.
Regards,
Tim

**Comment by lochmueller** [comment] 2020-03-15 17:04
Hey @Raymondsnijders 
I close this issue. The import process incl. the "Update" feature is only possible with ICS files, that do not change the identifier of the event on each load. If you have any other ideas for this problem, please send me a note or create a new issue.
Regards,
Tim

**Closed by lochmueller** 2020-03-15 17:04 UTC
Labels: bug
