### ISSUE TITLE
Frontend times differ by backend time by +1

### ISSUE THREAD

**Issue by c2po** [lochmueller/calendarize#16] opened 2015-10-26 17:27 UTC
Hi,
the start- and endtimes in the frontend have an offset by +1 which is not influenced by serverTimeZone. In the backend at the bottom of the calendarize tab they are right. The rendered times in frontend will be correct if using moment.js, but it would be nice to have correct times without javascript.

calendarize version: 1.6.1
calendarize_news: 0.3.0
[SYS][serverTimeZone] = 1
[SYS][phpTimeZone] = Europe/Berlin 
useMomentJsDateAndTimeOutput = 0

**Comment by lochmueller** [comment] 2015-10-26 20:12
Hey @c2po 
I can not reproduce this bug. Please add same more debug information (DB is right?). Do you check the index selection process?

Regards,
Tim

**Comment by c2po** [comment] 2015-10-27 14:15
Hi Tim,
thank you for your fast answer. In the calendarize configuration entry (in a news record) I only filled in the start_day (all others are zero or not visible). After saving the information at the bottom shows day and time 00:00-00:00. Then the model_index table start_date contains following correctly:

unixtime: 1447369200
GMT: Thu, 12 Nov 2015 23:00:00 GMT
local time: Fr 13 Nov 2015 00:00:00 CET GMT+1:00

(I used master from github and cleaned table model_index before.)
So the error must happen somewhere in the frontend rendering process.


Regards,
Daniel

**Comment by Schweriner** [comment] 2015-10-28 16:40
The problem is located at the parsing of the starttime from unixtime to a timestamp where one hour will be added by the format.date viewhelper because of the timezone.

**Comment by lochmueller** [comment] 2015-10-28 22:50
Thanks for your analysis @Schweriner 
Do you also have a smart solution/idea for this problem? If the date.format is the problem, the {index.startDate} in Resources/Private/Partials/Date/Static.html should be the right date (in e.g. f:debug), right?
Regards,
Tim

**Comment by Schweriner** [comment] 2015-10-29 07:34
Of course I did mean the parsing of unixtime to DateTime (not unixtime to timestamp haha)

Well the problem occurs because the format.date viewhelper will add the timezone to timestamps. A fast solution for the problem is using the "startDateComplete" which is already a DateTime object which won't be modified anymore and it contains the startTime of an event.

In the partial Date/Static.html example for the starttime:
<f:format.date format="{settings.timeFormat}">{index.startDateComplete}</f:format.date>

A smarter solution would be implementing a getter in the model which returns the starttime as a DateTime object.

Dirty but also possible: Parse the startTime by an own ViewHelper that converts the timestamp without adding the timezone and then give it to the format.date function.

Greetings from Schwerin, Germany

**Comment by lochmueller** [comment] 2015-10-29 08:36
Hey @Schweriner 
Hey @c2po 

I changed the timestamp part by the completeDateTime object of the index:
https://github.com/lochmueller/calendarize/commit/bcc8c99eba5aa761c9ebd683b8e197a32a3682b2

Please run a test with the current master.... I hope the patch solve the problem...

Regards,
Tim

**Comment by Schweriner** [comment] 2015-10-29 10:11
I already use it like this and it solves the problem for me.

**Comment by lochmueller** [comment] 2015-10-29 12:02
Great.... I close this issue.
@c2po If the problem still exists, please create a new issue here...

**Closed by lochmueller** 2015-10-29 12:02 UTC

**Comment by ses2013** [comment] 2020-11-03 09:49
In the database the value "start_time" is set to "72.000" when inserting "20:00" in the Backend.
So the FE value is correct as it reflects the database value:
In unix time 72.000 means 21:00.
So isn't there something wrong with the backend index? Making it "20:00" ?

**Comment by lochmueller** [comment] 2020-11-03 11:55
This is a TYPO3 core problem. Easiest solutation is, set the TYPO3 Installation to UTC via configuration. This avoid time shift issues and also solve problems related to dalight saving time.
