### ISSUE TITLE
Version number in composer manifest of package "calendarize" is missing or invalid

### ISSUE THREAD

**Issue by c2po** [lochmueller/calendarize#27] opened 2015-12-09 14:12 UTC
Hi,

newest version from TER (1.8.0) stops the extension manager (TYPO3 CMS 6.2.15) with above message. (also happened with newest autoloader.)

**Comment by lochmueller** [comment] 2015-12-09 21:13
Hey @c2po 
Do you find the mistake in the composer.json? Othe extensions also use no version number directly in the composer.json: https://git.typo3.org/TYPO3CMS/Extensions/news.git/blob_plain/c16829abe9d830a6b69072c7d862127deeeeb0a4:/composer.json

Regards,
Tim

**Comment by lochmueller** [comment] 2015-12-10 15:35
Hey @c2po 
It seems that this behavior is a core bug:
https://forge.typo3.org/issues/70175
https://forge.typo3.org/issues/70149#change-278682

The composer.json is right, but TYPO3 6.2 (in non composer mode) should fallback to the old file. I integration a solution, if the bug is solved in the core...

Regards,
Tim

**Comment by c2po** [comment] 2015-12-11 12:42
Hi Tim,
thanks for the hint. The core ticket is closed. Maybe it will never be solved for 6.2 LTS. 
For 6.2 Extension Manager users have the (less nice) option to delete the composer file.

Regards,
Daniel

**Comment by lochmueller** [comment] 2015-12-13 14:33
Hey @c2po 
the first issue is still open (https://forge.typo3.org/issues/70175). I close this issue here, because the problem is core related...
Regards,
Tim

**Closed by lochmueller** 2015-12-13 14:33 UTC
