### ISSUE TITLE
Copying records with date configuration results in a Start date one day before the Start date of the original record

### ISSUE THREAD

**Issue by timkarliczek** [lochmueller/calendarize#455] opened 2020-11-10 16:47 UTC
How to reproduce:

1. create a new event record (you can use the calendarize default event record for testing)
2. create a calendarize configuration
3. set a Start date
4. save the record
5. copy the record

This results in a start date one day before that of the original record.

![image](https://user-images.githubusercontent.com/26055407/98704291-c3a1a680-237c-11eb-85f5-dbc4bcb38bbc.png)

My setup:
- TYPO3 10.4.9
- current master of EXT:calendarize
- PHP 7.2
- PHP Default timezone Europe/Berlin

Does anyone has a solution for that?

**Comment by lochmueller** [comment] 2020-11-10 20:09
Hey @timkarliczek 
that is strange. In the background EXT:calendarize reindex the new record after the copy. But the copy process itself is not part of calendarize. Your records looks like the configuration record itself is shifted by one day. But this is not related to calendarize. I checked it with my installation and it looks great. Without time shift...
<img width="686" alt="Bildschirmfoto 2020-11-10 um 21 09 19" src="https://user-images.githubusercontent.com/3907126/98727937-083b3b00-2399-11eb-804e-dff2a807c1cd.png">

**Comment by timkarliczek** [comment] 2020-11-12 11:28
Thx for testing @lochmueller 
did you also have the timezone Europe/Berlin set?
I created a small ddev setup for testing this. Out of the box (timezone UTC) it works fine.
But when i set `timezone: Europe/Berlin` inside `.ddev/config.yaml` it behaves like in the issue description.
Maybe my setup is not correct or might this be a TYPO3 issue?

Anyway, this seems not to be a bug of EXT:calendarize. Every advice on how to handle this is welcome. Otherwise i will close this issue.

**Comment by okmiim** [comment] 2020-11-12 21:39
I can reproduce this bug.

I spend some time debugging and eventually found the bug inside **typo3 core**.
It is cause by the record copying process of typo3, where the value `2020-11-07` is parsed as date with the **local timezone**, converted to an timestamp `1604703600` (equals `2020-11-06T23:00:00 UTC`) and then reformatted with `gmdate` in the **UTC timezone** to `2020-11-06`.
This all happens inside [typo3/sysext/core/Classes/DataHandling/DataHandler.php->checkValueForInput()](https://github.com/TYPO3/TYPO3.CMS/blob/6d134bda6c0b16fabfe22ac5db61d6ad582db070/typo3/sysext/core/Classes/DataHandling/DataHandler.php#L1846).

For this bug plan to create an issue / try to contribute and fix this bug inside typo3 core soon.

**Comment by lochmueller** [comment] 2020-11-13 10:04
Hey @okmiim 
Thanks for investigation about this.
I close this issue.
Regards,
Tim

**Closed by lochmueller** 2020-11-13 10:04 UTC

**Comment by okmiim** [comment] 2020-12-22 18:12
Hey,
this bug is now fixed (see [master](https://review.typo3.org/c/Packages/TYPO3.CMS/+/66670), [10.4](https://review.typo3.org/c/Packages/TYPO3.CMS/+/67200)).

@lochmueller Please raise the minimum Typo3 version in the next release to 10.4.12

**Comment by lochmueller** [comment] 2020-12-22 22:16
@okmiim Done in current master.
