### ISSUE TITLE
Weekly dates indexed for wrong weekday

### ISSUE THREAD

**Issue by saneinsane** [lochmueller/calendarize#102] opened 2016-10-28 06:08 UTC
If I choose a start date later than 27.3.2016 for a weekly scheduled event, the indexed week day is shifted.

![screenshot ok 27.3.](https://cloud.githubusercontent.com/assets/9435220/19796517/4a40881e-9ce5-11e6-9fae-04b89deb62db.png)

![screenshot fail 28.3. ](https://cloud.githubusercontent.com/assets/9435220/19796516/4a2954aa-9ce5-11e6-8695-9d09b787ee4e.png)

(TYPO3 7.6.11, PHP 7.0.12, Calendarize 2.5.0)

**Comment by lochmueller** [comment] 2016-10-28 09:42
Hey... please run some debugging by your own in "\HDNET\Calendarize\Service\TimeTable\TimeTimeTable->addFrequencyItems". I cannot rebuild this problem on my Dev machine..
![screen](https://cloud.githubusercontent.com/assets/3907126/19802367/9ca62dde-9d03-11e6-8fe7-6607fcc5ed8b.png)

**Comment by saneinsane** [comment] 2016-10-28 11:39
Hi,

I could reproduce this on another machine with Calendarize 2.2.0.
27.3. was the day when summertime switched - this seems to be the reason for this.

The first loopItem for a weekly entry starting on 27.3.2016 (correct entry):

    [start_date] => DateTime Object
        (
            [date] => 2016-04-03 00:00:00.000000
            [timezone_type] => 1
            [timezone] => +01:00
        )

    [end_date] => DateTime Object
        (
            [date] => 2016-04-03 00:00:00.000000
            [timezone_type] => 1
            [timezone] => +01:00
        )

    [start_time] => 43800
    [end_time] => 45000
    [all_day] => 

The first loopItem for a weekly entry starting on 28.3.2016 (entry 1 day shifted):

    [start_date] => DateTime Object
        (
            [date] => 2016-04-04 00:00:00.000000
            [timezone_type] => 1
            [timezone] => +02:00
        )

    [end_date] => DateTime Object
        (
            [date] => 2016-04-04 00:00:00.000000
            [timezone_type] => 1
            [timezone] => +02:00
        )

    [start_time] => 43800
    [end_time] => 45000
    [all_day] => 

Both machines have correct php timezone entries (Europe/Berlin).

**Comment by saneinsane** [comment] 2016-10-30 08:39
Choosing Wednesday, 2. November (summertime ended) as start date, the indexed dates are correct.

**Comment by mminyades** [comment] 2016-11-01 09:26
i can confirm this bug.

by changing "weekStart" the frontend-output also shows empty columns.

screenshots:
![weeklybug](https://cloud.githubusercontent.com/assets/2368841/19885144/644fcf36-a01d-11e6-92b0-8974a44c5c06.jpg)

every event-entry was set to start on 04.04.2016

**Comment by lochmueller** [comment] 2016-11-01 10:19
@mminyades Thanks for your comment, but this seems to be a second problem. The topic is about wrong indexing in the backend (weekly events). Your screenshot shows wrong date selection in the FE related to the weekStart configuration. Pehaps you create a new issue?

**Comment by lochmueller** [comment] 2016-11-22 21:39
Perhaps this patch fix the issue. I will check this in the next days: https://github.com/lochmueller/calendarize/pull/113

**Comment by lochmueller** [comment] 2017-02-14 10:38
No more feedback.... there are also other tickets related to this one. I will close this issue... more details in: https://github.com/lochmueller/calendarize/issues/121

**Closed by lochmueller** 2017-02-14 10:38 UTC
