### ISSUE TITLE
error, if there is a Slash in an event title 

### ISSUE THREAD

**Issue by birgitberlin** [lochmueller/calendarize#378] opened 2020-03-02 09:52 UTC
If there is a slash in an event title, an error occures - in all views.

HDNET\Calendarize\Service\Url\Typo3Route::id2alias

Line 62:
$alias = $slugHelper->sanitize($alias);
does not remove "/"
You have to add:
$alias = str_replace('/','-',$alias);

In general:
It could be better to add a slug field to the event table and use the field configuration for sanitizing the title.

**Comment by claude27** [comment] 2020-03-02 10:12
+1 
is perhaps a regression caused by a recent change, as we had the problem some time ago https://github.com/lochmueller/calendarize/issues/357

**Comment by lochmueller** [comment] 2020-03-05 08:03
Hey @birgitberlin 
Thanks for reporting. Fixed in current master and next release.
Regards,
Tim

**Closed** 2020-03-05 08:03 UTC
Labels: bug
