### ISSUE TITLE
ICS import ignores begin:daylight / tzoffset

### ISSUE THREAD

**Issue by kweidler** [lochmueller/calendarize#543] opened 2021-04-17 09:06 UTC
TYPO3 10.4.14, calendarize 9.0.

If an ICS file is imported via the scheduler, the part "beginn:daylight" is ignored. The appointment "Termin Sommerzeit" is imported and displayed with the times 10 - 11 am. The correct time would be 9 - 10 am.
The appointment "Termin Winterzeit" is correctly imported and displayed with 9 - 10 am.

When importing UTC data, the service works correctly, but these are not supported by the planned source system.

Many thanks for your efforts!

My ics-file:
```BEGIN:VCALENDAR
VERSION:2.0
PRODID:Import-Demo
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:CET
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:Central European Summer Time
DTSTART:20160327T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:Central European Time
DTSTART:20161030T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:Import-Demo-1
LOCATION:Demodorf
SUMMARY:Termin Sommerzeit
DESCRIPTION:Ich bin die Beschreibung
CLASS:PUBLIC
DTSTART;TZID=CET:20210420T090000
DTEND;TZID=CET:20210420T100000
DTSTAMP:20210417T102015
END:VEVENT
BEGIN:VEVENT
UID:Import-Demo-2
LOCATION:Demodorf
SUMMARY:Termin Winterzeit
DESCRIPTION:Ich bin die Beschreibung
CLASS:PUBLIC
DTSTART;TZID=CET:20211120T090000
DTEND;TZID=CET:20211120T100000
DTSTAMP:20210417T102015
END:VEVENT
END:VCALENDAR

**Comment by okmiim** [comment] 2021-04-17 11:19
Hi @kweidler,
I can confirm this behavior.
The ical parsing is done in composer mode by [sabre-io/vobject](https://github.com/sabre-io/vobject). As far as I looked it does not respect multiple `VTIMEZONE` for the dates.

In this extension we get only DateTime Objects with `CET` timezone (constant, independent from summertime switch) and convert them to `Europe/Berlin` (local TZ), resulting in the time shift. This step / conversion itself is correct.

So this is **not supported** and I see no easy way to implement this.

---

If you control the source I recommend you to switch from `CET` / `CEST` to e.g. `Europe/Berlin` (DST / summertime aware).
An alternative is to preprocess the ical.

_Note_: Your example is missing `BEGIN:VCALENDAR`

**Comment by kweidler** [comment] 2021-04-17 12:49
Thank you for your feedback. Then I'll see if we can adjust the source.

`BEGIN:VCALENDAR` was accidentally omitted during copying. ;-)

**Comment by lochmueller** [comment] 2021-07-19 20:57
Hey @kweidler 
I will close this issue because it is based on the parser. If you found a good solution, feel free to share the solution with us.
Regards,
Tim

**Closed by lochmueller** 2021-07-19 20:57 UTC
