### ISSUE TITLE
Translated record not be indexing for the Ke_search.

### ISSUE THREAD

**Issue by nilesh-nitsan** [lochmueller/calendarize#419] opened 2020-08-25 06:47 UTC
I have tried with TYPO3 9.5.20, Calendarize version 6.0.0 but I have faced this issue first while translating record
https://i.imgur.com/zfz5iCF.png

Second thing, when I trying to indexing from the Ke_search it can not be indexing translated record. 
It is working fine with the default language.

Is there any solution for this?

Thanks!

**Comment by lochmueller** [comment] 2020-08-25 13:12
Hey @nilesh-nitsan ,
The problem is fixed with this commit: https://github.com/lochmueller/calendarize/commit/d82761af288f548574943f6681d7aecc9163fb8f
If you need this for old TYPO3 Installations/Calendarize versions, please backport the changes by yourself.
Regards,
Tim

**Closed** 2020-08-25 13:11 UTC
